version: 0.2

phases:
  install:
    runtime-versions:
      java: 11

  pre_build:
    commands:
      - echo "Executing pre-build commands"
      # Add any pre-build commands or scripts here

  build:
    commands:
      - echo "Executing build commands"
      - mvn clean install  # Assuming you are using Maven for your Java project

  post_build:
    commands:
      - echo "Executing post-build commands"
      # Add any post-build commands or scripts here

artifacts:
  files: '**/*'
  discard-paths: yes
